apiVersion: v1
kind: ConfigMap
metadata:
  name: wailsalutem-backend-config
  namespace: wailsalutem-suite
data:

  DB_HOST: postgresql
  DB_PORT: "5432"
  DB_NAME: WailSalutem_Suite_DB
  
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  
  KEYCLOAK_BASE_URL: https://keycloak-wailsalutem-suite.apps.inholland-minor.openshift.eu
  KEYCLOAK_REALM: wailsalutem
  KEYCLOAK_API_CLIENT_ID: wailsalutem-api
  KEYCLOAK_ADMIN_CLIENT_ID: wailsalutem-admin