apiVersion: v1
kind: ConfigMap
metadata:
  name: wailsalutem-backend-config
  namespace: wailsalutem-suite
data:

  DB_HOST: postgresql
  DB_PORT: "5432"
  DB_NAME: WailSalutem_Suite_DB
  
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  
  KEYCLOAK_BASE_URL: https://keycloak-wailsalutem-suite.apps.inholland-minor.openshift.eu
  KEYCLOAK_REALM: wailsalutem
  KEYCLOAK_API_CLIENT_ID: wailsalutem-api
  KEYCLOAK_ADMIN_CLIENT_ID: wailsalutem-admin
  
  ALLOWED_ORIGINS: "http://localhost:3000,https://wailsalutem-web-ui.netlify.app,https://wailsalutem-suite.netlify.app"
  
  # OpenTelemetry Configuration
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector.observability.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "organization-service"
  OTEL_SERVICE_NAMESPACE: "wailsalutem"
  OTEL_SERVICE_VERSION: "1.0.0"
  ENVIRONMENT: "production"
  OTEL_TRACES_SAMPLER: "always_on"
  OTEL_METRICS_EXPORT_INTERVAL: "30s"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_INSECURE: "true"