apiVersion: v1
kind: Secret
metadata:
  name: wailsalutem-backend-secrets
  namespace: wailsalutem-suite
type: Opaque
stringData:

  DB_USER: superadmin
  DB_PASSWORD: WailSalutemDB2026!
  
  RABBITMQ_USER: wailsalutem
  RABBITMQ_PASSWORD: WailSalutemRMQ2026!
  
  KEYCLOAK_ADMIN_CLIENT_SECRET: 7tQrsHdQqcnbTcJPwJWqQaGhJG4Jlxdr