apiVersion: v1
kind: Secret
metadata:
  name: github-deployer-token
  namespace: wailsalutem-suite
  annotations:
    kubernetes.io/service-account.name: github-deployer
type: kubernetes.io/service-account-token
