apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-service
  namespace: wailsalutem-suite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organization-service
  template:
    metadata:
      labels:
        app: organization-service
    spec:
      containers:
          - name: organization-service
          image: organization-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: wailsalutem-backend-config
            - secretRef:
                name: wailsalutem-backend-secrets