apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: organization-service
  namespace: wailsalutem-suite
spec:
  to:
    kind: Service
    name: organization-service
  port:
    targetPort: http
  tls:
    termination: edge